// packages/react/src/line.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  type CanvasHTMLAttributes,
} from "react";
import type { DeepPartial, Viewport } from "@sixtyfold/core";
import {
  LineChart,
  type LineAppearanceOptions,
  type LineChartOptions,
  type LineChartStats,
  type LineDataUpdateOptions,
  type SeriesVisibilityChangeEvent,
} from "@sixtyfold/line";
import { hasViewport, installLineData, type ChartHandle, type LineData } from "./shared.js";

export type LineChartHandle = ChartHandle<LineChart>;

export interface SixtyfoldLineChartProps extends Omit<
  CanvasHTMLAttributes<HTMLCanvasElement>,
  "children"
> {
  /** Construction-time options. Remount the component to replace them. */
  options?: LineChartOptions;
  /**
   * One-shot chart data. Supply a new object for each update. Worker mode
   * transfers and detaches its buffers; main-thread mode retains references.
   */
  data?: LineData;
  dataUpdateOptions?: LineDataUpdateOptions;
  /** Reactive visual patch applied without recreating the chart. */
  appearance?: DeepPartial<LineAppearanceOptions>;
  /** Reactive viewport patch. */
  viewport?: Partial<Viewport>;
  /** Leave undefined to inherit the chart's configured `animated` default. */
  viewportAnimated?: boolean;
  onReady?: (chart: LineChart) => void;
  /** Reports construction, renderer, and overlay-image failures. */
  onError?: (error: unknown) => void;
  onStats?: (stats: LineChartStats) => void;
  statsIntervalMs?: number;
  onSeriesVisibilityChange?: (event: SeriesVisibilityChangeEvent) => void;
}

/** React host for a Sixtyfold line chart. DOM work starts after mount, so SSR emits only the canvas. */
export const SixtyfoldLineChart = forwardRef<LineChartHandle, SixtyfoldLineChartProps>(
  function SixtyfoldLineChart(
    {
      options,
      data,
      dataUpdateOptions,
      appearance,
      viewport,
      viewportAnimated,
      onReady,
      onError,
      onStats,
      statsIntervalMs,
      onSeriesVisibilityChange,
      style,
      ...canvasProps
    },
    forwardedRef,
  ) {
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const chartRef = useRef<LineChart | null>(null);
    const initialOptionsRef = useRef(options);
    const latestRef = useRef({
      data,
      dataUpdateOptions,
      appearance,
      viewport,
      viewportAnimated,
      onReady,
      onError,
      onStats,
      statsIntervalMs,
      onSeriesVisibilityChange,
    });
    const readyRef = useRef(false);
    const appliedDataRef = useRef<LineData | undefined>(undefined);
    const appliedAppearanceRef = useRef<DeepPartial<LineAppearanceOptions> | undefined>(undefined);
    const appliedViewportRef = useRef<Partial<Viewport> | undefined>(undefined);

    useImperativeHandle(
      forwardedRef,
      () => ({
        get chart() {
          return chartRef.current;
        },
      }),
      [],
    );

    // Publish only committed props. Mutating this ref during render can expose
    // values from a concurrent render that React later abandons.
    useEffect(() => {
      latestRef.current = {
        data,
        dataUpdateOptions,
        appearance,
        viewport,
        viewportAnimated,
        onReady,
        onError,
        onStats,
        statsIntervalMs,
        onSeriesVisibilityChange,
      };
    }, [
      appearance,
      data,
      dataUpdateOptions,
      onError,
      onReady,
      onSeriesVisibilityChange,
      onStats,
      statsIntervalMs,
      viewport,
      viewportAnimated,
    ]);

    // Installs every reactive prop in a single engine update. Each dataset
    // object is applied at most once and never before the chart is ready.
    // Worker mode transfers its buffers; identity tracking also prevents
    // duplicate installs in main-thread mode.
    const applyReactiveProps = useCallback((): void => {
      const chart = chartRef.current;
      if (!readyRef.current || !chart) return;
      const current = latestRef.current;
      chart.batch(() => {
        if (current.data && current.data !== appliedDataRef.current) {
          installLineData(chart, current.data, current.dataUpdateOptions);
          appliedDataRef.current = current.data;
        }
        if (current.appearance && current.appearance !== appliedAppearanceRef.current) {
          chart.updateAppearance(current.appearance);
          appliedAppearanceRef.current = current.appearance;
        }
        if (hasViewport(current.viewport) && current.viewport !== appliedViewportRef.current) {
          chart.setViewport(current.viewport, { animated: current.viewportAnimated });
          appliedViewportRef.current = current.viewport;
        }
      });
    }, []);

    useEffect(() => {
      let disposed = false;
      let mountedChart: LineChart | null = null;

      // Deferring construction by one microtask prevents React Strict Mode's
      // development-only setup/cleanup probe from installing data twice.
      queueMicrotask(() => {
        if (disposed || !canvasRef.current) return;
        let chart: LineChart;
        try {
          chart = new LineChart(canvasRef.current, initialOptionsRef.current ?? {});
        } catch (error) {
          // Construction is deferred into a microtask, so a throw here would
          // otherwise escape as an uncaught error no error boundary can see.
          if (!disposed) latestRef.current.onError?.(error);
          return;
        }
        mountedChart = chart;
        chartRef.current = chart;
        let reportedRendererError: unknown;
        chart.setRendererErrorCallback((error) => {
          reportedRendererError = error;
          if (!disposed) latestRef.current.onError?.(error);
        });
        chart.setOverlayErrorCallback((error) => {
          if (!disposed) latestRef.current.onError?.(error);
        });
        const latest = latestRef.current;
        chart.setStatsCallback(
          latest.onStats ? (stats) => latestRef.current.onStats?.(stats) : null,
          { intervalMs: latest.statsIntervalMs },
        );
        chart.setSeriesVisibilityCallback((event) => {
          latestRef.current.onSeriesVisibilityChange?.(event);
        });

        void chart
          .initialize()
          .then(() => {
            if (disposed || chartRef.current !== chart) return;
            readyRef.current = true;
            applyReactiveProps();
            latestRef.current.onReady?.(chart);
          })
          .catch((error) => {
            if (!disposed && error !== reportedRendererError) {
              latestRef.current.onError?.(error);
            }
          });
      });

      return () => {
        disposed = true;
        readyRef.current = false;
        if (chartRef.current === mountedChart) chartRef.current = null;
        mountedChart?.destroy();
      };
    }, [applyReactiveProps]);

    useEffect(() => {
      applyReactiveProps();
    }, [applyReactiveProps, data, dataUpdateOptions, appearance, viewport, viewportAnimated]);

    useEffect(() => {
      const chart = chartRef.current;
      if (!chart) return;
      chart.setStatsCallback(onStats ? (stats) => latestRef.current.onStats?.(stats) : null, {
        intervalMs: statsIntervalMs,
      });
    }, [onStats, statsIntervalMs]);

    return (
      <canvas
        aria-label={options?.interactive === false ? "Chart" : "Interactive chart"}
        role={options?.interactive === false ? "img" : "application"}
        tabIndex={options?.interactive === false ? undefined : 0}
        {...canvasProps}
        ref={canvasRef}
        style={{ display: "block", width: "100%", height: "100%", ...style }}
      />
    );
  },
);

// packages/svelte/src/line.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { DeepPartial, Viewport } from "@sixtyfold/core";
  import {
    LineChart,
    type LineAppearanceOptions,
    type LineChartOptions,
    type LineChartStats,
    type LineDataUpdateOptions,
    type SeriesVisibilityChangeEvent,
  } from "@sixtyfold/line";
  import { hasViewport, installLineData, type LineData } from "./shared.js";

  /** Construction-time options. Remount the component to replace them. */
  export let options: LineChartOptions = {};
  /**
   * One-shot chart data. Assign a new object for each update. Worker mode
   * transfers and detaches its buffers; main-thread mode retains references.
   */
  export let data: LineData | undefined = undefined;
  export let dataUpdateOptions: LineDataUpdateOptions | undefined = undefined;
  export let appearance: DeepPartial<LineAppearanceOptions> | undefined = undefined;
  export let viewport: Partial<Viewport> | undefined = undefined;
  /** Leave undefined to inherit the chart's configured `animated` default. */
  export let viewportAnimated: boolean | undefined = undefined;
  export let statsIntervalMs: number | undefined = undefined;
  export let onReady: ((chart: LineChart) => void) | undefined = undefined;
  /** Reports construction, renderer, and overlay-image failures. */
  export let onError: ((error: unknown) => void) | undefined = undefined;
  export let onStats: ((stats: LineChartStats) => void) | undefined = undefined;
  export let onSeriesVisibilityChange: ((event: SeriesVisibilityChangeEvent) => void) | undefined =
    undefined;
  export let canvasClass = "";
  export let canvasStyle = "";
  export let ariaLabel: string | undefined = undefined;
  export let ariaDescribedBy: string | undefined = undefined;
  export let canvasRole: string | undefined = undefined;
  export let canvasTabIndex: number | undefined = undefined;
  /** Bindable access to the mounted imperative chart. */
  export let chart: LineChart | null = null;

  // Assigned by Svelte's bind:this directive.
  // oxlint-disable-next-line no-unassigned-vars
  let canvas: HTMLCanvasElement;
  let ready = false;
  let disposed = false;
  let reportedRendererError: unknown;
  let appliedData: LineData | undefined;
  let appliedAppearance: DeepPartial<LineAppearanceOptions> | undefined;
  let appliedViewport: Partial<Viewport> | undefined;

  // The arguments are the reactive dependencies; the body reads them directly
  // so a single change installs data, appearance, and viewport in one update.
  $: applyReactiveProps(ready, chart, data, appearance, viewport, viewportAnimated);
  $: if (chart) {
    chart.setStatsCallback(onStats ? (stats) => onStats?.(stats) : null, {
      intervalMs: statsIntervalMs,
    });
  }

  // Each dataset object is applied at most once. Worker mode transfers its
  // buffers; identity tracking also prevents duplicate installs in main-thread
  // mode.
  function applyReactiveProps(
    isReady: boolean,
    instance: LineChart | null,
    nextData: LineData | undefined,
    nextAppearance: DeepPartial<LineAppearanceOptions> | undefined,
    nextViewport: Partial<Viewport> | undefined,
    animated: boolean | undefined,
  ): void {
    if (!isReady || !instance) return;
    instance.batch(() => {
      if (nextData && nextData !== appliedData) {
        installLineData(instance, nextData, dataUpdateOptions);
        appliedData = nextData;
      }
      if (nextAppearance && nextAppearance !== appliedAppearance) {
        instance.updateAppearance(nextAppearance);
        appliedAppearance = nextAppearance;
      }
      if (hasViewport(nextViewport) && nextViewport !== appliedViewport) {
        instance.setViewport(nextViewport, { animated });
        appliedViewport = nextViewport;
      }
    });
  }

  onMount(() => {
    let instance: LineChart;
    try {
      instance = new LineChart(canvas, options);
    } catch (error) {
      if (!disposed) onError?.(error);
      return;
    }
    chart = instance;
    instance.setRendererErrorCallback((error) => {
      reportedRendererError = error;
      if (!disposed) onError?.(error);
    });
    instance.setOverlayErrorCallback((error) => {
      if (!disposed) onError?.(error);
    });
    instance.setSeriesVisibilityCallback((event) => onSeriesVisibilityChange?.(event));
    void instance
      .initialize()
      .then(() => {
        if (disposed || chart !== instance) return;
        ready = true;
        onReady?.(instance);
      })
      .catch((error) => {
        if (!disposed && error !== reportedRendererError) onError?.(error);
      });
    return () => {
      disposed = true;
      ready = false;
      instance.destroy();
      if (chart === instance) chart = null;
    };
  });
</script>

<canvas
  bind:this={canvas}
  class={canvasClass}
  style={`display:block;width:100%;height:100%;${canvasStyle}`}
  aria-label={ariaLabel ?? (options.interactive === false ? "Chart" : "Interactive chart")}
  aria-describedby={ariaDescribedBy}
  role={canvasRole ?? (options.interactive === false ? "img" : "application")}
  tabindex={canvasTabIndex ?? (options.interactive === false ? undefined : 0)}
></canvas>
